target 'ios' do
  use_frameworks!
  platform :ios, '17.0'
  pod 'shared', :path => '../shared'
end

target 'osx' do
  platform :osx, '14.0'
  pod 'shared', :path => '../shared'
end

target 'SalahTimes Watch App' do
  platform :watchos, '10.0'
  pod 'shared', :path => '../shared'
end

target 'ios-compose' do
  use_frameworks!
  platform :ios, '17.0'
  pod 'renderer', :path => '../renderer'
end
